# Site Settings
title: Hack the Burgh
email: htb@comp-soc.com	
description: "Major League Hacking hits Edinburgh"
baseurl: "http://compsoc-edinburgh.github.io/hacktheburgh/"
url: "http://compsoc-edinburgh.github.io/hacktheburgh/"
author: "CompSoc"

# Main Navigation (Manual)
navigation:
 - text: Home
   url: /
 - text: Where is HTB?
   url: "#map"

# Build Settings
paginate: 3
paginate_path: "blog/page:num"
markdown: kramdown
permalink: pretty
